"""
Inject JSON-LD FAQ schema into editorial posts — batch 3.
Skips posts that already have schema markup.
"""
import json
from pathlib import Path

FAQS = {
    'sleep-paralysis-explained.html': [
        ("What is sleep paralysis?",
         "Sleep paralysis is a temporary inability to move or speak that occurs when transitioning between sleep and wakefulness — usually when waking from REM sleep. During REM, the brain paralyzes voluntary muscles to prevent acting out dreams (REM atonia). Sleep paralysis occurs when this atonia persists briefly after consciousness returns. Episodes last seconds to a few minutes and resolve spontaneously. It is not dangerous, though it can be frightening, especially when accompanied by hallucinations."),
        ("Why does sleep paralysis happen?",
         "Sleep paralysis occurs when REM atonia (the muscle paralysis normal during REM sleep) extends into the waking state. Risk factors include sleep deprivation, irregular sleep schedules, sleeping on your back, high stress, narcolepsy, and certain medications. It is most common during the transition from REM to waking — in the morning or during daytime naps. It affects approximately 8% of the general population and up to 28% of college students."),
        ("How do I stop sleep paralysis?",
         "Sleep paralysis episodes typically end on their own within 1-5 minutes. To exit more quickly: try moving your eyes or wiggling a finger or toe — small movements can break the paralysis before large ones. Steady breathing helps. Preventively: maintain consistent sleep and wake times, avoid sleeping supine (back sleeping is the highest-risk position), address sleep deprivation, and manage stress. Recurring sleep paralysis warrants evaluation for narcolepsy."),
        ("Are sleep paralysis hallucinations real?",
         "They are real perceptions but not reflective of external reality. Sleep paralysis hallucinations are hypnagogic (occurring at sleep onset) or hypnopompic (occurring at waking) experiences generated by the dreaming brain as consciousness partially returns. They commonly include a sense of a presence in the room, visual figures, chest pressure (the 'old hag' experience), and sounds. Cultural interpretations vary widely, but the neurological explanation is consistent across populations."),
    ],
    'hypnic-jerk-explained.html': [
        ("What is a hypnic jerk?",
         "A hypnic jerk (also called a sleep start or hypnagogic jerk) is an involuntary muscle contraction that occurs at the boundary between wakefulness and sleep, usually during Stage 1 sleep onset. It often involves a sudden sensation of falling, accompanied by a full-body jerk. Hypnic jerks are experienced by 60-70% of people and are entirely normal — they are not a sign of any neurological condition."),
        ("Why do hypnic jerks happen?",
         "The mechanism is not fully understood, but the leading theories involve: the relaxation paradox (as the brain transitions to sleep and motor control relaxes, a misinterpretation triggers a reflexive muscle contraction), a protective reflex (evolutionary response to prevent falling from perches during sleep onset), or an artifact of the changing electrical activity as the brain shifts from waking to sleeping states. Hypnic jerks are more frequent when overtired, highly caffeinated, or anxious."),
        ("Are hypnic jerks a sign of a problem?",
         "Occasional hypnic jerks are completely normal and require no treatment. Frequent, severe hypnic jerks that prevent sleep onset may indicate sleep deprivation, excessive caffeine, high stress, or — rarely — a movement disorder. If jerks occur throughout sleep (not just at onset), are accompanied by pain, or progressively worsen, evaluation by a neurologist is warranted to rule out periodic limb movement disorder or myoclonic epilepsy."),
        ("How do I stop hypnic jerks?",
         "Most people do not need to treat them. Frequency tends to reduce with: consistent sleep schedule (reducing accumulated sleep deprivation), limiting caffeine especially after noon, managing stress and anxiety before bed, and avoiding strenuous exercise in the 2-3 hours before bed. Progressive muscle relaxation before sleep can reduce the frequency in people who experience disruptive hypnic jerks."),
    ],
    'couples-sleep-problems.html': [
        ("Should couples sleep in separate beds?",
         "Separate sleeping (sleep divorce) is increasing and is a legitimate solution for couples whose sleep is significantly disrupted by snoring, movement, or schedule differences. Research shows couples who sleep separately often report better individual sleep quality. The decision should be mutual and framed as a sleep health strategy, not a relationship statement. Many couples maintain intimacy through transition rituals (falling asleep together, then separating) while protecting sleep quality."),
        ("Does snoring affect your partner's health?",
         "Yes. Bed partners of loud snorers lose an average of 1 hour of sleep per night and have elevated rates of daytime sleepiness, mood disruption, and relationship strain. Chronic sleep loss in the non-snoring partner has the same health consequences as their own poor sleep — increased cardiovascular risk, impaired immunity, and cognitive decline. The snoring partner's health risk (often sleep apnea) also requires attention, making snoring a dual health concern."),
        ("What is the best sleeping position for couples?",
         "There is no universally 'best' position. The most common couple positions and their sleep implications: back-to-back with slight contact allows independent temperature regulation and minimizes sleep disruption; spooning requires coordinated movement and generates heat; face-to-face is rare during extended sleep but common when falling asleep. Synchronized movement between partners is associated with higher relationship satisfaction in some studies, but individual sleep quality takes priority for health."),
        ("How do you sleep with a partner who has a different sleep schedule?",
         "Key strategies: use blackout curtains so the early riser's departure doesn't wake the late sleeper; use a white noise machine to mask exit sounds; establish a light-off time agreed upon by both partners for the early sleeper's needs; the late sleeper reads in another room if needed. Circadian chronotype differences are largely genetic — the solution is logistics, not asking the night owl to become a morning person."),
    ],
    'sleep-paralysis-explained.html': [],  # placeholder to avoid duplicate key
    'hypnic-jerk-explained.html': [],  # placeholder
    'sleep-chronotypes.html': [
        ("What is a sleep chronotype?",
         "A chronotype is your genetically determined circadian preference — the timing at which your body clock naturally schedules sleep, wakefulness, peak alertness, and hormone release. Morning types (larks) have an earlier circadian phase; evening types (owls) have a delayed phase. Chronotype is approximately 50% heritable and shifts across the lifespan: children are morning types, adolescents shift dramatically toward evening, and adults gradually shift back toward morning after age 50-60."),
        ("How do I find out my chronotype?",
         "The Munich Chronotype Questionnaire (MCTQ) and the Morningness-Eveningness Questionnaire (MEQ) are the most validated tools — both available free online. The simplest practical measure: on days with no alarm or obligations, what time do you naturally fall asleep and wake? Your midpoint of natural sleep is your chronotype indicator. Consistent patterns across multiple free days give the most reliable result."),
        ("Can you change your chronotype?",
         "Chronotype is largely genetic but not immovable. Light therapy in the morning can advance an evening chronotype by 1-2 hours over 2-4 weeks. Consistent early wake times, morning exercise, and meal timing reinforce phase advances. However, attempting to force a strong evening type into a morning type schedule creates chronic circadian misalignment — social jet lag — which has documented metabolic and cardiovascular health costs."),
        ("Does being a night owl mean poor sleep?",
         "No — evening chronotypes have physiologically normal sleep; it is just timed later. The problem is structural misalignment with early school and work start times. Evening chronotypes forced into early schedules experience chronic sleep deprivation and circadian disruption — not because their sleep is defective, but because society's schedule is misaligned with their biology. Late-starting work schedules eliminate this penalty entirely."),
    ],
    'sleep-debt-accumulation.html': [
        ("What is sleep debt?",
         "Sleep debt is the cumulative deficit between the sleep you need and the sleep you get. It operates as a genuine physiological state — not just a metaphor. Each hour of insufficient sleep adds to the debt, and the health and performance consequences compound over time. A week of sleeping 6 hours per night (2 hours short of typical need) creates 14 hours of sleep debt with measurable cognitive, metabolic, and hormonal consequences that exceed a single night of total deprivation."),
        ("Does sleep debt accumulate permanently?",
         "Sleep debt from short-term restriction (days to weeks) is largely reversible with recovery sleep. However, the cognitive impairment from chronic sleep restriction does not feel as severe as it actually is — people adapt their subjective sense of sleepiness without recovering performance. Some research suggests that 2-3 weeks of chronic restriction may cause structural neurological changes that are not fully reversed by a single recovery night."),
        ("How much sleep debt is too much?",
         "Any consistent shortfall matters. Studies show measurable cognitive impairment begins after 16-17 consecutive hours of wakefulness — equivalent to cutting sleep short by 1 hour per night for several days. Sleeping 6 hours nightly for two weeks produces performance impairment equivalent to two consecutive nights of total sleep deprivation, while subjects feel only mildly sleepy. There is no 'safe' level of chronic sleep restriction below individual sleep need."),
        ("Is there a way to avoid accumulating sleep debt?",
         "Yes: sleep enough each night (7-8 hours for most adults), maintain consistent sleep timing, and address the structural factors that cause restriction — late-night screen use, stress, irregular schedules. If debt accumulates during a high-demand week, prioritize extra sleep on the first available nights rather than waiting for the weekend. A nap of 20-60 minutes can partially offset single-night restrictions."),
    ],
    'sleep-debt-recovery.html': [
        ("How long does it take to recover from sleep deprivation?",
         "Recovery from mild-to-moderate acute sleep debt (1-2 weeks of restriction) takes approximately 1-2 weeks of adequate sleep. The subjective sense of being rested returns within 1-3 recovery nights; objective cognitive performance takes longer to normalize. Metabolic markers (insulin sensitivity, cortisol patterns) may require 2-3 weeks to fully restore. For chronic sleep debt lasting months, full recovery may require an extended period of consistently adequate sleep."),
        ("Can you make up for lost sleep on weekends?",
         "Partially, and with trade-offs. Sleeping extra on weekends reduces some accumulated sleep debt and partially restores cognitive performance. However, it also shifts sleep timing (creating social jet lag), which disrupts circadian rhythm and makes Monday morning harder. The net effect for chronically sleep-deprived people is typically negative — weekend catch-up provides incomplete recovery while perpetuating circadian instability. Building adequate nightly sleep is more effective than cycling through debt and recovery."),
        ("Do naps help with sleep debt?",
         "Yes, for acute sleep debt. A 20-60 minute nap partially restores alertness and some cognitive functions after a poor night. Naps cannot fully compensate for chronic restriction but are the best tool for managing acute debt (after a flight, an all-nighter, or an unexpectedly poor night). Naps should be taken before 3pm and limited to 20 minutes (Stage 2 sleep) or 90 minutes (full cycle) to avoid sleep inertia and nighttime sleep disruption."),
        ("What foods help recover from sleep deprivation?",
         "No food directly compensates for sleep debt, but certain nutritional strategies support recovery: adequate protein supports the growth hormone-driven tissue repair that occurs during recovery sleep; complex carbohydrates support serotonin production which supports REM sleep; magnesium-rich foods (leafy greens, nuts, seeds) support the GABA system that deepens sleep. Caffeine can support performance during recovery but should be stopped by 2pm to allow recovery sleep to be high-quality."),
    ],
    'sleep-exercise-timing.html': [
        ("Does the time of day you exercise affect sleep?",
         "Yes. Morning exercise is associated with the greatest sleep benefit: it reinforces circadian rhythm through light exposure, raises core temperature that subsequently drops (promoting sleep), and depletes adenosine that deepens subsequent sleep. Afternoon exercise (3-5pm) aligns with the body temperature and cardiovascular performance peak and produces good sleep outcomes. Evening exercise (within 2 hours of bed) can delay sleep onset in some people by elevating core temperature and sympathetic nervous system activity."),
        ("Can you exercise too close to bedtime?",
         "For most people, vigorous exercise within 60-90 minutes of bed elevates heart rate, core temperature, and cortisol in ways that delay sleep onset. However, this effect is individual — some people sleep fine after evening workouts. Light exercise (yoga, stretching, walking) close to bedtime is generally beneficial for sleep and does not cause the same arousal. If you must exercise in the evening, a cool shower afterward can help counteract the temperature elevation."),
        ("Does exercise help with insomnia?",
         "Yes — moderate aerobic exercise is one of the strongest behavioral interventions for insomnia outside of CBT-I. A meta-analysis of 17 randomized controlled trials found that regular aerobic exercise reduces sleep onset latency by approximately 17 minutes, increases total sleep time by 40 minutes, and improves sleep quality scores significantly. Effects accumulate over 4-8 weeks; sleep does not dramatically improve after a single session."),
        ("How much exercise do you need for better sleep?",
         "150 minutes per week of moderate aerobic activity (the general health recommendation) produces significant sleep benefits. More is generally better up to a point — elite athletes sleeping 9-10 hours per night during training periods demonstrate the sleep benefits of high activity loads. For sedentary individuals, even 30 minutes of brisk walking 3x per week produces measurable sleep quality improvement within 4-6 weeks."),
    ],
    'sleep-food-connection.html': [
        ("What foods promote sleep?",
         "Foods with evidence for sleep support: tart cherry juice (natural melatonin + anti-inflammatory compounds, 2 studies showing reduced insomnia symptoms), kiwifruit (serotonin precursors + antioxidants, 4-week trial showing 35% reduction in sleep onset latency), turkey and other tryptophan-rich foods (tryptophan is the dietary precursor to serotonin and melatonin), and warm milk (tryptophan + the psychological cue of a warm calming ritual). Fatty fish, nuts, and seeds provide magnesium and omega-3s that support sleep architecture."),
        ("What foods disrupt sleep?",
         "The main disruptors: caffeine (blocks adenosine; found in coffee, tea, energy drinks, chocolate, and some medications — half-life 5-7 hours), alcohol (suppresses REM and causes rebound arousal), high-glycemic foods within 3 hours of bed (blood sugar spike and crash can disrupt sleep mid-night), spicy foods (raise core temperature and cause heartburn), and large meals within 2-3 hours of bedtime (digestion elevates metabolic rate and body temperature during the period when both should be declining)."),
        ("Does eating before bed cause weight gain?",
         "Total daily caloric intake determines weight gain — not meal timing alone. However, late-night eating tends to correlate with higher overall calorie intake and is associated with weight gain in observational studies. Metabolically, insulin sensitivity is lower in the evening, meaning the same calories are handled less efficiently than earlier in the day. For sleep, heavy late meals increase body temperature and digestive activity that can fragment sleep."),
        ("What is the best dinner for good sleep?",
         "Moderate portion size (avoid large meals within 3 hours of bed), balanced macronutrients with an emphasis on complex carbohydrates over simple sugars (supports serotonin synthesis without blood sugar spikes), moderate protein (tryptophan precursor), and low fat (delays gastric emptying, which can worsen reflux). Specific combinations: salmon with sweet potato and leafy greens; turkey with quinoa and vegetables; Greek yogurt with berries. Avoid spicy, acidic, or very fatty meals in the evening."),
    ],
    'sleep-apnea-diagnosis.html': [
        ("How is sleep apnea diagnosed?",
         "Sleep apnea is diagnosed through a sleep study. A polysomnography (PSG) in a sleep laboratory is the gold standard — it measures brain waves, oxygen levels, heart rate, breathing, eye and leg movements simultaneously. Home sleep apnea tests (HSAT) measure airflow, respiratory effort, and oxygen saturation and are prescribed for uncomplicated suspected OSA. The severity metric is the Apnea-Hypopnea Index (AHI): mild OSA is 5-14 events/hour, moderate 15-29, severe 30+."),
        ("Can I diagnose sleep apnea at home?",
         "You can identify warning signs at home (snoring, witnessed apneas, excessive daytime sleepiness, morning headaches) but cannot diagnose it without a sleep study. Consumer sleep trackers that estimate sleep stages are not validated for OSA diagnosis. Your doctor can order a home sleep apnea test (HSAT) — a portable device worn one night at home — which is covered by most insurance for suspected OSA and provides definitive diagnosis for most cases."),
        ("What is the difference between OSA and central sleep apnea?",
         "Obstructive sleep apnea (OSA) occurs when the airway physically collapses during sleep, blocking airflow despite continued breathing effort. Central sleep apnea (CSA) occurs when the brain fails to send the breathing signal appropriately — the airway is open but breathing stops. OSA is far more common (95% of cases). CSA is associated with heart failure, stroke, opioid use, and high altitude. Both show on sleep studies as cessation of airflow, but respiratory effort differentiates them."),
        ("How long does a sleep apnea test take?",
         "A home sleep apnea test (HSAT) is typically done on one night. You pick up the device, sleep at home with sensors measuring airflow, effort, and oxygen, and return it the next day. Results are reviewed by a sleep physician within a few days. A full in-lab polysomnography requires one full night (typically 8pm-6am). Some diagnoses require both a diagnostic night and a CPAP titration night, though split-night studies can accomplish both in one visit."),
    ],
    'sleep-genetics.html': [
        ("Is sleep quality genetic?",
         "Yes, substantially. Twin studies show that approximately 40-55% of variance in insomnia symptoms, sleep duration preference, and sleep architecture is heritable. Specific genes affecting sleep include PER2 (delayed sleep phase), CLOCK (circadian period length), and DEC2 (the rare 'short sleeper' mutation). Genetic variants in adenosine-processing genes affect caffeine sensitivity and sleep pressure accumulation. Sleep genetics is an active research area — some findings are replicated; many are preliminary."),
        ("What is the short sleeper gene?",
         "The DEC2 mutation (p.Pro385Arg) is the best-characterized 'short sleeper' variant. Carriers naturally sleep approximately 6 hours per night and wake refreshed, without cognitive or health impairment seen in most short sleepers. It is extremely rare — estimated at under 3% of the population. The widespread belief that 'I'm just someone who needs less sleep' is almost never validated by this mutation; most self-reported short sleepers are simply adapted to sleep deprivation."),
        ("Can genetics cause insomnia?",
         "Yes. Genome-wide association studies have identified 202 genetic loci associated with insomnia risk. The condition appears polygenic — many small-effect variants contribute rather than a single deterministic gene. Genetic risk for insomnia overlaps significantly with genetic risk for anxiety and depression, supporting the view that insomnia, anxiety, and depression share biological pathways. Having genetic risk does not mean insomnia is inevitable — environmental and behavioral factors strongly moderate expression."),
        ("Does sleep apnea run in families?",
         "Yes. First-degree relatives of sleep apnea patients have 2-4x higher OSA risk than the general population. The heritability of OSA is estimated at 35-40%. Genetic factors that contribute include craniofacial anatomy (jaw size, position of the hyoid bone), obesity predisposition, and ventilatory control stability. Having a parent or sibling with diagnosed OSA is a meaningful risk factor that should prompt evaluation if symptoms develop."),
    ],
    'daylight-saving-sleep.html': [
        ("How does daylight saving time affect sleep?",
         "The spring forward transition (losing one hour) creates acute circadian disruption equivalent to mild jet lag. For the week following, studies document: increased sleep deprivation (average 40-50 minutes lost), 6-24% increase in heart attacks (multiple US studies), higher stroke incidence, increased fatal car accidents, and reduced workplace productivity. The fall back transition is less disruptive but still disrupts circadian timing for sensitive individuals."),
        ("How long does it take to adjust to daylight saving time?",
         "The spring transition typically requires 3-7 days of adjustment for most people. Evening chronotypes (night owls) adapt faster to spring forward; morning chronotypes struggle more. Melatonin at 0.5mg taken 30 minutes before the new target bedtime for 3-4 nights accelerates the circadian adjustment. Morning light exposure at the new wake time also accelerates adaptation."),
        ("How do I minimize the effects of daylight saving time?",
         "For spring forward: begin shifting bedtime 15 minutes earlier starting 3-4 days before the transition; ensure bright morning light at the new wake time; limit evening light exposure; take 0.5mg melatonin at the new bedtime for the first 3-4 nights. For fall back: maintain a consistent wake time (resist the urge to sleep an extra hour indefinitely); use the additional evening darkness productively for earlier wind-down."),
        ("Should daylight saving time be eliminated?",
         "Most sleep medicine professional societies — including the American Academy of Sleep Medicine — formally advocate for the permanent elimination of time changes and adoption of permanent standard time (not permanent DST). Permanent standard time better aligns with human circadian biology, which is entrained to solar noon, not clock noon. The cardiovascular and accident data from the spring transition make DST a documented public health hazard."),
    ],
    'menopause-sleep.html': [
        ("Why does menopause cause sleep problems?",
         "Menopause disrupts sleep through multiple mechanisms simultaneously. Hot flashes and night sweats (vasomotor symptoms) wake 60-80% of menopausal women from sleep by activating the body's heat response. Declining estrogen reduces slow-wave sleep time and increases sleep fragmentation. Progesterone's GABAergic sleep-promoting effects are lost. Depression and anxiety, which are more common during perimenopause, independently disrupt sleep. Sleep apnea incidence triples after menopause, as estrogen's protective effect on upper airway muscle tone is lost."),
        ("How do I stop waking up from hot flashes at night?",
         "Immediate interventions: keep bedroom at 63-65°F, use moisture-wicking bedding, wear breathable cotton or cooling-fabric sleepwear, and keep a fan or cooling towel accessible. Medical interventions with the strongest evidence: menopausal hormone therapy (MHT) reduces vasomotor symptoms by 75-90%; low-dose paroxetine (Brisdelle, the only FDA-approved non-hormonal drug for hot flashes); and gabapentin taken at bedtime (off-label but effective). Discuss with a gynecologist."),
        ("Does HRT (hormone replacement therapy) help with sleep in menopause?",
         "Yes, when vasomotor symptoms are the primary driver. Menopausal hormone therapy (MHT) significantly reduces hot flash frequency and severity, which in turn reduces night wakings. It also has direct effects on sleep architecture — progesterone has GABAergic properties that promote slow-wave sleep. The current evidence supports MHT as safe for most women under 60 or within 10 years of menopause onset for symptom management, though individual risk-benefit assessment with a physician is essential."),
        ("What supplements help with menopause sleep?",
         "Magnesium glycinate (200-400mg) supports GABA pathways and helps reduce the physiological hyperarousal component of menopause insomnia. Black cohosh has modest evidence for hot flash reduction — some women report benefit. Low-dose melatonin (0.5mg) is useful if sleep timing has shifted. Phytoestrogens (soy isoflavones) have inconsistent evidence. None approach the efficacy of MHT for vasomotor-driven sleep disruption."),
    ],
    'sleep-mental-health.html': [
        ("How does sleep affect mental health?",
         "Sleep and mental health have a profound bidirectional relationship. Sleep deprivation activates the amygdala (emotional reactivity center) by 60% and reduces prefrontal regulation of emotion. Chronic sleep deprivation increases risk of depression by 2-5x and anxiety disorders by 2-3x. Conversely, virtually all mental health conditions disrupt sleep. Addressing sleep is now considered a central component of mental health treatment — not a secondary outcome."),
        ("Can improving sleep improve mental health?",
         "Yes — there is strong evidence that sleep improvement produces direct mental health benefit. Studies where insomnia is treated separately from depression show that insomnia remission reduces depression relapse rate and speeds recovery. CBT-I delivery to people with anxiety disorders reduces both sleep problems and anxiety severity. The mechanism involves normalizing REM sleep (which processes emotional memories), reducing cortisol (elevated by sleep deprivation), and restoring prefrontal regulation of the amygdala."),
        ("What mental health conditions cause sleep problems?",
         "Depression (insomnia or hypersomnia in 90% of cases), anxiety disorders (sleep onset insomnia, hyperarousal), PTSD (nightmares, fragmented sleep, hypervigilance), bipolar disorder (dramatically reduced sleep need during mania, hypersomnia in depression), ADHD (delayed sleep phase, insomnia), schizophrenia (severely fragmented sleep, reduced slow-wave sleep), and OCD (bedtime rituals that delay sleep). Each condition disrupts sleep through different mechanisms requiring targeted approaches."),
        ("Is poor sleep a cause or a symptom of mental illness?",
         "Both — and the bidirectionality is well-established. Sleep disruption precedes and predicts the onset of depression and anxiety in longitudinal studies, suggesting it is more than a symptom. The neurobiological mechanisms (cortisol elevation, amygdala hyperreactivity, emotional memory dysregulation) are specific pathways through which poor sleep contributes to mental illness. Treating sleep disorder separately from mental illness produces independent mental health improvements, supporting sleep as a causal contributor."),
    ],
    'sleep-when-anxious.html': [
        ("How do I fall asleep when my mind won't stop?",
         "The most effective techniques for cognitive arousal at bedtime: scheduled worry time (30 minutes in the afternoon to write down and process concerns, reducing the need to process them at bedtime), cognitive defusion ('I am having the thought that...' rather than engaging with content), and stimulus control (leaving bed after 20 minutes of wakefulness, returning only when sleepy). Physiological techniques: physiological sighing (double inhale through nose, long exhale through mouth) rapidly reduces sympathetic arousal within seconds to minutes."),
        ("Does anxiety cause insomnia or does insomnia cause anxiety?",
         "Both, through different mechanisms. Anxiety activates the HPA axis and sympathetic nervous system, creating the hyperarousal that prevents sleep onset and maintenance. Insomnia then generates sleep anxiety — fear of not sleeping — that creates a secondary anxiety loop independent of the original anxiety. This dual pathway is why people with anxiety-driven insomnia continue to have insomnia even when their anxiety otherwise improves: the conditioned arousal and sleep anxiety now maintain insomnia autonomously."),
        ("What breathing technique helps sleep?",
         "Physiological sighing is the fastest-acting: a double inhale through the nose (sniff to maximum capacity, then a second small sniff to fully inflate the lungs), followed by a long, slow exhale through the mouth. This maximally deflates alveoli that collapse during normal breathing, offloading CO2 and triggering parasympathetic activation within 1-2 breaths. 4-7-8 breathing (inhale 4 counts, hold 7, exhale 8 counts) is effective over 5-10 minutes for sustained arousal reduction."),
        ("Should I take medication for anxiety-related insomnia?",
         "CBT-I is the first-line treatment for anxiety-related insomnia and is more effective long-term than medication. For short-term relief during acute high-anxiety periods, low-dose options (magnesium glycinate, L-theanine) can support sleep without dependency risk. Prescription sedatives provide faster relief but cause tolerance and rebound. If anxiety disorders are severe enough to require pharmacological treatment, working with a psychiatrist to choose options with minimal sleep disruption (avoiding benzodiazepines for long-term use) is the recommended approach."),
    ],
    'sleep-light-therapy.html': [
        ("What is light therapy and how does it help sleep?",
         "Light therapy uses a bright (typically 10,000-lux) lamp to deliver concentrated bright light exposure that mimics the circadian signal of morning sunlight. It works by activating intrinsically photosensitive retinal ganglion cells (ipRGCs), which suppress melatonin and advance the circadian clock. It is first-line treatment for seasonal affective disorder (SAD), delayed sleep phase disorder, and circadian disruption from shift work and jet lag. Ten to thirty minutes each morning produces clinically significant effects."),
        ("Does light therapy work for insomnia?",
         "Light therapy specifically targets circadian insomnia — insomnia driven by misaligned sleep timing rather than hyperarousal. For delayed sleep phase (inability to fall asleep until very late), morning light therapy advances the clock and shifts the sleep window earlier within 1-4 weeks. For non-dipping circadian patterns (poor circadian amplitude), regular morning light strengthens the rhythm. It is less effective for insomnia driven primarily by anxiety or hyperarousal."),
        ("When should I use a light therapy lamp?",
         "Within 30-60 minutes of waking, ideally at the same time each day. The circadian clock is most responsive to light during the first 2 hours after natural wake time — earlier in the period produces more phase advance. Do not use light therapy in the evening or late afternoon if your goal is to advance (earlier) sleep timing — this will delay the clock instead. Duration: 20-30 minutes at 10,000 lux, or 40-60 minutes at 5,000 lux."),
        ("Can light therapy replace antidepressants for SAD?",
         "Light therapy is as effective as antidepressants for seasonal affective disorder in multiple randomized controlled trials. The combination of light therapy plus antidepressants is more effective than either alone for severe SAD. For mild-to-moderate SAD with a clear seasonal pattern and circadian disruption, light therapy is the preferred first-line treatment due to rapid onset (1-2 weeks), tolerability, and absence of systemic side effects. Consult a physician for severe SAD or bipolar disorder."),
    ],
    'altitude-sleep.html': [
        ("Why is sleep difficult at high altitude?",
         "High altitude reduces atmospheric oxygen pressure, causing periodic breathing — a cycle of hyperventilation and apnea (Cheyne-Stokes respiration) that fragments sleep. The hypoxia triggers compensatory breathing changes that overshoot and then undershoot CO2 levels in a recurring cycle, interrupting sleep every 60-90 seconds in severe cases. Most people experience disrupted sleep for 2-7 nights at elevations above 8,000 feet (2,400m), with gradual acclimatization."),
        ("How do I sleep better at high altitude?",
         "Acclimatization is the primary solution — ascend gradually (no more than 1,000 feet/300m gain per day above 8,000 feet). Acetazolamide (Diamox), a prescription medication, accelerates acclimatization and reduces periodic breathing significantly; take it 24 hours before ascent. Sleep at a lower altitude if possible (climb high, sleep low). Avoid alcohol and sedatives, which worsen the periodic breathing cycle. Supplemental oxygen dramatically improves sleep quality when available."),
        ("Does altitude affect deep sleep?",
         "Yes. Slow-wave sleep is suppressed at altitude, and REM sleep is reduced, with most of the sleep architecture shifting toward lighter stages. The periodic breathing cycle interrupts the deeper sleep stages. Cognitive performance, which depends heavily on slow-wave and REM sleep, is measurably impaired during the first several days at altitude even in well-acclimatized individuals — relevant for mountaineers and athletes at elevation."),
        ("When does sleep normalize at altitude?",
         "Most people experience significant improvement within 3-7 days at a given altitude as the peripheral chemoreceptors recalibrate to the lower oxygen environment. Sleep at 8,000-10,000 feet typically normalizes within 3-5 days. Higher altitudes (above 14,000 feet/4,300m) may continue to disrupt sleep for longer; full acclimatization at extreme altitude (above 18,000 feet) may take 2-3 weeks and is never complete."),
    ],
    'sleep-exam-study.html': [
        ("Is it better to study or sleep before an exam?",
         "Sleep before an exam consistently outperforms all-night studying. Sleep consolidates the material studied during the preceding days — without sleep, up to 40% of newly learned information fails to transfer to long-term memory. Studying all night produces fatigue and impaired retrieval during the exam that erases the marginal benefit of the extra study time. The optimal strategy is studying well in the days prior and protecting sleep on the night before."),
        ("Does pulling an all-nighter before an exam help?",
         "No — it typically makes exam performance worse. All-nighters reduce working memory by 20-40%, reaction time, and retrieval speed. The material crammed during the all-night session is poorly consolidated without subsequent sleep. Combined with the alertness deficit during the exam, the trade-off is negative for most students. Short-term adrenaline during the exam masks fatigue but does not restore the cognitive capabilities impaired by sleep deprivation."),
        ("How much sleep do students need during exam period?",
         "7-8 hours minimum, ideally consistent with the student's normal sleep schedule. Exam stress compresses study time and often creates the conditions for sleep restriction — the inverse of what sleep science recommends. Students who maintain regular sleep during exam periods outperform those who sacrifice sleep to study more, because memory consolidation (which requires sleep) is the critical bottleneck in exam performance."),
        ("What is the best nap strategy during exam preparation?",
         "A 20-minute power nap improves alertness and working memory for 2-3 hours — useful between study sessions without disrupting nighttime sleep. A 90-minute nap (full sleep cycle) produces stronger memory consolidation and is worth taking after a study session if nighttime sleep was short the previous night. Avoid naps after 3pm and longer than 90 minutes, which disrupt nighttime sleep when it matters most."),
    ],
    'sleep-after-covid.html': [
        ("Does COVID-19 cause sleep problems?",
         "Yes — sleep disturbance is one of the most common Long COVID symptoms, reported in 40-60% of those with prolonged post-COVID symptoms. Manifestations include insomnia, hypersomnia, unrefreshing sleep, and new-onset sleep apnea. The mechanisms include neuroinflammation affecting sleep-regulatory brain regions, autonomic nervous system dysregulation (elevated nighttime heart rate, impaired HRV), and the psychological burden of prolonged illness."),
        ("How long do COVID sleep problems last?",
         "For most people, acute COVID-related sleep disruption resolves within 4-8 weeks of illness recovery. For Long COVID patients, sleep symptoms are among the most persistent — some studies report significant sleep dysfunction 12-18 months post-infection. The prognosis varies widely: patients with mild acute illness and short duration have the best outcomes; those with severe initial illness or significant autonomic dysregulation have longer recovery timelines."),
        ("What helps with post-COVID insomnia?",
         "The same evidence-based approaches as other insomnia: CBT-I (first-line, addresses the behavioral component), consistent sleep timing, stimulus control, and sleep hygiene. For autonomic dysregulation driving nighttime symptoms: elevation of the head of bed can reduce nighttime heart rate variability disruption; pacing (avoiding post-exertional malaise triggers during recovery) may reduce nighttime sympathetic activation. If sleep apnea is suspected post-COVID, a home sleep test is warranted."),
        ("Did COVID-19 cause a sleep epidemic?",
         "Population-level data confirm significant increases in insomnia rates during and after the COVID-19 pandemic. A global meta-analysis found insomnia prevalence more than doubled during the pandemic — from roughly 15% to over 40% in some populations. Contributing factors include: disrupted routines, reduced light exposure from indoor confinement, increased stress and anxiety, reduced physical activity, and increased screen time. This has been termed 'coronasomnia' in public health literature."),
    ],
    'napping-science.html': [
        ("What are the benefits of napping?",
         "Research-documented napping benefits: improved alertness (by clearing adenosine that accumulates with waking), enhanced motor learning and procedural memory consolidation, restored cardiovascular function (blood pressure dips with short naps), improved mood and emotional regulation, and enhanced creative problem-solving when the nap includes REM sleep. NASA found that 26-minute naps improved pilot performance by 34% and alertness by 100%."),
        ("How long should a nap be for maximum benefit?",
         "Depends on the goal: 10-20 minutes captures Stage 1-2 sleep (alertness boost, easy awakening); 60 minutes includes slow-wave sleep (memory consolidation, physical recovery) but risks mild sleep inertia; 90 minutes completes one full sleep cycle including REM (emotional processing, creative problem-solving, maximum consolidation) with minimal sleep inertia. The 20-minute 'power nap' optimizes benefit-to-awakening-ease ratio for most purposes."),
        ("What is the best time to take a nap?",
         "1pm-3pm aligns with the natural post-lunch circadian dip (a documented secondary nadir in alertness occurring approximately 7-8 hours after waking). Napping during this window uses a natural energy trough rather than fighting the circadian system. Napping after 3pm risks encroaching on nighttime sleep drive and delaying bedtime. Morning naps are efficient for REM recovery but indicate inadequate nighttime sleep."),
        ("Does napping at work improve productivity?",
         "Yes, with robust evidence. Multiple workplace studies show 20-minute naps improve afternoon performance, error rates, and decision-making quality. Google, Nike, NASA, and Ben & Jerry's provide nap facilities. In countries with established siesta cultures, afternoon nap breaks are associated with lower cardiovascular disease rates. The primary barrier is cultural — napping is still associated with laziness in many workplace environments despite clear productivity evidence."),
    ],
    'sleep-and-hormones.html': [
        ("How does sleep affect hormones?",
         "Sleep regulates virtually every major hormonal system. Growth hormone is released primarily during slow-wave sleep (70% of daily output). Cortisol follows a tight circadian pattern — nadir at midnight, peak at 30-45 minutes after waking. Insulin sensitivity is highest in the morning and decreases throughout the day — disrupted sleep impairs this rhythm. Ghrelin (hunger hormone) rises and leptin (satiety hormone) falls with sleep deprivation. Testosterone is produced primarily during sleep and is measurably reduced after even one week of short sleep in men."),
        ("Does poor sleep lower testosterone?",
         "Yes. A week of sleeping 5 hours per night reduces testosterone levels by 10-15% in young healthy men — equivalent to 10-15 years of aging. REM sleep is the primary testosterone production window; alcohol and REM-suppressing drugs correspondingly reduce testosterone output. The effect is reversible with sleep restoration. For men concerned about testosterone optimization, sleep is the most impactful modifiable factor before considering supplementation."),
        ("Does sleep affect cortisol?",
         "Profoundly. Cortisol follows one of the most robust circadian rhythms in the body, peaking in the cortisol awakening response (30-45 minutes after waking) and reaching its nadir around midnight. Sleep deprivation elevates daytime cortisol by 37-45% and blunts the circadian rhythm amplitude. Elevated nighttime cortisol fragments sleep and delays melatonin onset, creating a self-reinforcing cycle. Stress management and consistent sleep timing are the primary interventions for cortisol dysregulation."),
        ("Does sleep affect thyroid hormones?",
         "Yes, though the relationship is complex. TSH (thyroid-stimulating hormone) peaks during the night in synchrony with the circadian clock, with the highest secretion occurring during sleep. Sleep deprivation elevates daytime TSH and T3 levels, which may contribute to the metabolic changes seen with chronic poor sleep. People with hypothyroidism often report sleep problems — inadequately treated hypothyroidism causes insomnia and sleep apnea through multiple mechanisms."),
    ],
    'summer-sleep-guide.html': [
        ("Why is it harder to sleep in summer?",
         "Summer disrupts sleep through three main mechanisms: longer daylight hours delay melatonin onset (light at 9pm in summer keeps the brain in daytime mode), higher ambient temperatures prevent the core body temperature drop required for sleep initiation and maintenance, and the shift in social schedules (later activities, irregular routines) creates circadian disruption. For those in northern latitudes with very long summer days, the circadian impact is particularly strong."),
        ("What is the best bedroom temperature for summer sleep?",
         "The target is 65-68°F (18-20°C) — the same as winter. In summer heat, achieving this may require: air conditioning, ceiling fans (which increase convective cooling even without lowering temperature significantly), cooling mattress pads, and breathable linen or moisture-wicking bedding. If air conditioning is unavailable, sleeping at the lowest floor of the house (cooler air sinks), using ice packs near the bed, and opening windows after dark (when outdoor temperature falls below indoor temperature) are effective alternatives."),
        ("How do I sleep in summer without air conditioning?",
         "Effective strategies: thermal mass principle (keep windows and curtains closed during the day to prevent heat entry; open them after dark when outdoor temperature drops); Egyptian method (lightly mist sheets with water and use a fan — evaporative cooling significantly reduces skin temperature); place ice in a bowl in front of a fan to create cool air flow; sleep on the lowest floor; use breathable cotton or linen rather than synthetic materials; freeze a hot water bottle and use it to pre-cool the bed."),
        ("Does summer light affect melatonin?",
         "Significantly. Light exposure until 8-9pm in summer suppresses melatonin production and delays sleep onset by 1-2 hours compared to winter. This is the main reason many people find it harder to fall asleep and wake up on summer mornings. Blackout curtains in the bedroom prevent early morning light (5-6am in summer) from suppressing melatonin prematurely. Amber-lens glasses worn after 7pm in summer preserve melatonin onset without requiring total darkness."),
    ],
    'winter-sleep-guide.html': [
        ("Why do people sleep more in winter?",
         "Shorter winter days mean more darkness, which extends melatonin secretion duration — the body produces melatonin for longer when nights are longer. This biologically promotes earlier sleep onset and later waking. Colder temperatures reduce basal metabolic rate (less energy available for activity) and facilitate the core body temperature drop that promotes sleep. Winter also brings more indoor isolation, reduced physical activity, and lower vitamin D levels — all of which affect sleep quality."),
        ("Does cold weather help you sleep?",
         "Cool-to-cold bedroom temperatures (65-68°F) genuinely improve sleep quality — this is one of the most well-established environmental sleep factors. However, temperatures below 60°F can prevent the body from maintaining the stable core temperature needed for restorative sleep. The ideal is a cool bedroom with adequate blankets — the insulating layer allows core temperature to drop slightly while protecting against excessive cold."),
        ("What is seasonal affective disorder and how does it affect sleep?",
         "Seasonal affective disorder (SAD) is a recurrent depression pattern with onset in fall/winter and remission in spring/summer. Sleep changes are a core symptom: hypersomnia (sleeping 10+ hours, difficulty waking), morning fatigue despite extended sleep, carbohydrate craving, and low energy. The mechanism involves extended melatonin secretion in reduced winter light and serotonin pathway disruption. Morning light therapy (10,000 lux, 20-30 minutes upon waking) is first-line treatment and reverses sleep symptoms within 1-2 weeks."),
        ("How does vitamin D affect winter sleep?",
         "Vitamin D deficiency, common in northern latitudes during winter, is associated with poorer sleep quality, shorter sleep duration, and higher rates of sleep disorders. Vitamin D receptors are found in brain regions governing sleep (suprachiasmatic nucleus, hypothalamus). Supplementation with 2,000-4,000 IU daily has shown modest sleep quality improvement in deficient individuals in randomized trials. A 25-OH vitamin D blood test is the most direct way to assess whether deficiency is contributing to winter sleep problems."),
    ],
    'weekend-sleep-mistake.html': [
        ("Why is sleeping in on weekends bad for sleep?",
         "Sleeping in on weekends shifts your circadian clock later — each hour of extra weekend sleep delays melatonin onset by approximately 30-45 minutes. By Sunday night, your body clock is running 1-2 hours behind your weekday schedule, making it harder to fall asleep at the weekday bedtime and creating the 'social jet lag' effect that peaks on Monday morning. The chronic oscillation between weekday and weekend sleep schedules prevents the circadian stability needed for consistent, high-quality sleep."),
        ("Is it OK to sleep in occasionally?",
         "An occasional extra 30-60 minutes on weekends has minimal circadian impact and can partially address accumulated sleep debt. The problem is chronic large-amplitude shifts (2+ hours) every weekend, which constitute a recurring phase shift. The solution is not perfect rigidity but variance reduction: keeping wake times within 1 hour across all 7 days is sufficient for circadian stability."),
        ("What is the right way to catch up on sleep?",
         "The most effective catch-up strategy is going to bed earlier on Friday and Saturday (earlier bedtime moves sleep forward without pushing wake time back significantly), supplemented by a 20-minute nap if needed during the day. This accumulates extra sleep without shifting the clock later. Sleeping in late — the instinctive catch-up strategy — delays the clock and creates the Monday morning problem it was trying to solve."),
        ("How do I fix my sleep schedule after sleeping in all weekend?",
         "Monday morning: get up at your target wake time regardless of how tired you feel. Expose yourself to bright light immediately upon waking (outdoors or 10,000-lux lamp). Avoid naps Monday to maintain sleep pressure for Monday night. Take 0.5mg melatonin 30 minutes before your weekday target bedtime Monday and Tuesday nights. Maintain this for 3-4 days and the clock re-synchronizes."),
    ],
    'magnesium-deficiency-sleep.html': [
        ("Does magnesium deficiency cause insomnia?",
         "Magnesium deficiency is associated with poor sleep quality, difficulty falling asleep, frequent nocturnal awakenings, and restless legs syndrome. The mechanism involves magnesium's role as a cofactor for GABA synthesis and its direct binding to GABA-A receptors (the same receptors targeted by benzodiazepines). Deficiency reduces GABAergic tone, increasing physiological hyperarousal. Approximately 48% of Americans consume below the estimated average requirement for magnesium."),
        ("How do I know if I'm magnesium deficient?",
         "Serum magnesium testing is standard but insensitive — only severe deficiency shows on serum levels since the body pulls magnesium from bone to maintain serum concentration. RBC (red blood cell) magnesium is more sensitive. Functional indicators include: muscle cramps (especially nocturnal), restless legs, irritability, anxiety, constipation, poor sleep quality, and sensitivity to noise. A therapeutic trial of magnesium glycinate (200-400mg for 4-6 weeks) is both diagnostic and potentially therapeutic."),
        ("What foods are highest in magnesium?",
         "Dark leafy greens (spinach: 157mg/cup cooked), pumpkin seeds (156mg/oz), black beans (120mg/cup), edamame (100mg/cup), dark chocolate 70%+ (64mg/oz), nuts (almonds: 80mg/oz), avocado (58mg per medium), and whole grains. The RDA for magnesium is 320mg for adult women and 420mg for adult men. Modern agricultural soil depletion means food magnesium content is approximately 30% lower than historical values, making dietary sufficiency harder to achieve."),
        ("Is it safe to take magnesium every night for sleep?",
         "Yes. Magnesium glycinate at 200-400mg nightly is well-tolerated and safe for long-term use in most adults. Unlike pharmacological sleep aids, magnesium does not produce tolerance, dependency, or rebound insomnia. The main side effect at high doses (>600mg) is loose stools — the glycinate form has the lowest laxative effect of all magnesium forms. People with kidney disease should consult a physician before supplementing, as impaired kidney function reduces magnesium excretion."),
    ],
}

# Remove placeholder duplicates
FAQS = {k: v for k, v in FAQS.items() if v}


def make_schema(faqs):
    entities = []
    for q, a in faqs:
        entities.append({
            "@type": "Question",
            "name": q,
            "acceptedAnswer": {"@type": "Answer", "text": a}
        })
    schema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": entities
    }
    return '<script type="application/ld+json">\n' + json.dumps(schema, indent=2) + '\n</script>'


updated = 0
skipped = 0
for fname, faqs in FAQS.items():
    p = Path(f'posts/{fname}')
    if not p.exists():
        print(f'MISSING: {fname}')
        continue
    html = p.read_text(encoding='utf-8')
    if 'application/ld+json' in html:
        print(f'SKIP (has schema): {fname}')
        skipped += 1
        continue

    schema_block = make_schema(faqs)
    if '</head>' in html:
        html = html.replace('</head>', schema_block + '\n</head>', 1)
        p.write_text(html, encoding='utf-8')
        print(f'OK: {fname} ({len(faqs)} Q&As)')
        updated += 1
    else:
        print(f'NO HEAD TAG: {fname}')

print(f'\nUpdated: {updated}  Skipped: {skipped}')
