"""Add FAQPage schema to 24 product posts that are missing it."""
import os, json, re

POSTS_DIR = 'posts'
BASE_URL = 'https://sleepwisereviews.com/posts/'

FAQ_DATA = {
    'best-anti-snoring-devices': [
        ('Do anti-snoring devices actually work?', 'It depends on the cause. Mandibular advancement devices (MADs) are effective for positional snoring and mild sleep apnea -- studies show 50-80% reduction in snoring in compliant users. Nasal dilators help snoring caused by nasal congestion. Tongue-retaining devices work for tongue-based airway collapse. No single device works for everyone; the cause of snoring determines which device will help.'),
        ('What is the difference between a MAD and a chin strap?', 'A mandibular advancement device (MAD) is worn in the mouth and physically repositions the lower jaw forward, opening the airway. A chin strap wraps under the chin to keep the mouth closed, which only helps mouth-breathers. MADs are more effective for most snoring causes; chin straps are simpler but help fewer people.'),
        ('When should snoring be evaluated by a doctor?', 'See a doctor if snoring is accompanied by gasping, choking, or long pauses in breathing -- these are signs of obstructive sleep apnea (OSA). Also see a doctor if snoring causes excessive daytime sleepiness, morning headaches, or your partner notices you stop breathing during sleep. OSA requires medical diagnosis and treatment beyond OTC anti-snoring devices.'),
    ],
    'best-aromatherapy-sleep': [
        ('Does aromatherapy actually improve sleep?', 'Some essential oils -- particularly lavender -- have clinical evidence for modest sleep improvement. A 2015 meta-analysis in the Journal of Alternative and Complementary Medicine found lavender improved sleep quality in 15 of 22 studies. The mechanism is likely activation of the parasympathetic nervous system through olfactory pathways. Effects are real but generally modest -- aromatherapy works best as part of a wind-down routine rather than as a standalone insomnia treatment.'),
        ('Which essential oil is best for sleep?', 'Lavender has the most clinical evidence and is the first choice for sleep aromatherapy. Bergamot, Roman chamomile, and ylang-ylang also have some supporting research. Valerian oil (not to be confused with valerian root supplements) is traditionally used for sleep but has less modern clinical evidence. Blend diffusion -- combining lavender with bergamot -- may be more effective than single oils.'),
        ('Is it safe to diffuse essential oils all night?', 'No. Run a diffuser for 30-60 minutes before and at the start of sleep, then turn it off. Continuous diffusion can cause headaches, dizziness, and in sensitive individuals, respiratory irritation. Some pets (especially cats) are sensitive to certain essential oils. Never apply undiluted essential oils directly to skin.'),
    ],
    'best-blackout-curtains': [
        ('What percentage of light do blackout curtains block?', 'True blackout curtains block 99-100% of light. "Room darkening" curtains typically block 85-99%. The difference matters: even 1% light leakage can affect melatonin suppression, especially blue-spectrum light. Look for triple-weave, foam-backed, or thermal-lined curtains for maximum blackout performance.'),
        ('Do blackout curtains also reduce noise?', 'Yes. Blackout curtains are typically heavier than standard curtains, which gives them sound-dampening properties. Thermal-lined and foam-backed blackout curtains can reduce external noise by 5-7 dB -- enough to reduce street noise meaningfully. They are not soundproof, but are noticeably quieter than thin curtains or bare windows.'),
        ('How do I prevent light gaps around blackout curtains?', 'Use curtain rods that extend 4-6 inches beyond the window frame on each side. Choose curtains that are at least 2-3 inches wider than the window on each side and extend to the floor. For ceiling-level installation, mount the rod as close to the ceiling as possible. Use blackout curtain liners behind existing curtains for gaps at the top.'),
    ],
    'best-blue-light-glasses': [
        ('Do blue light glasses improve sleep?', 'The evidence is mixed but promising. A 2021 study in Current Biology found wearing blue-light-blocking glasses 3 hours before bed improved sleep quality and increased sleep duration by 24 minutes. However, the largest effects came from amber-tinted lenses that block the full visible blue/green spectrum (380-550nm), not clear "computer glasses" that filter only a small portion of blue light. If you want sleep benefits, choose amber lenses for evening use.'),
        ('What is the difference between clear and amber blue light glasses?', 'Clear blue light glasses filter 30-40% of blue light and are appropriate for daytime computer use to reduce eye strain. Amber blue light glasses filter 80-100% of blue wavelengths (and sometimes green as well) and are effective for melatonin preservation 2-3 hours before bed. For sleep benefits, clear lenses are insufficient -- use amber lenses in the evening.'),
        ('When should I start wearing blue light glasses before bed?', 'For meaningful melatonin preservation, start 2-3 hours before your intended sleep time. The critical window is 2 hours before bed when melatonin production begins to ramp up. Wearing them from 8pm if you sleep at 10pm creates a meaningful difference in sleep-onset time and sleep quality.'),
    ],
    'best-cooling-mattress-pads': [
        ('Do cooling mattress pads actually work?', 'Yes, but the mechanism varies by type. Active cooling pads (water-circulating, like Eight Sleep or BedJet) can reduce mattress surface temperature by 10-20 degrees and have the strongest clinical effect. Phase-change material (PCM) pads absorb heat passively and reduce temperature by 3-5 degrees. Wool and cotton pads improve moisture wicking but do not actively cool. Active systems work best; passive materials help but cannot match active cooling for severe hot sleepers.'),
        ('What is the difference between a mattress pad and a mattress topper?', 'A mattress pad is thin (0.5-2 inches) and primarily affects surface temperature, moisture management, and minor softness. A mattress topper is thicker (2-4+ inches) and changes the firmness and pressure-relief profile of your mattress. For cooling only, a pad is sufficient. For cooling plus firmness adjustment, consider a topper with cooling properties.'),
        ('Can a cooling mattress pad damage my mattress?', 'Standard mattress pads and most passive cooling pads pose no risk to mattresses. Water-circulating pads carry a small risk of leaks; quality brands include leak detection. Always follow manufacturer instructions for your mattress warranty -- some warranties require specific pad/topper types. Memory foam mattresses can trap heat from the pad itself, reducing cooling effectiveness.'),
    ],
    'best-cooling-pillows': [
        ('What is the coolest pillow filling?', 'Latex and buckwheat hull are the coolest natural pillow fills -- both have open structures that allow airflow through the pillow. Shredded memory foam with gel infusion is cooler than solid memory foam. Water-filled pillows (like Mediflow) maintain cool temperature throughout the night. Down and down alternative trap heat and are the warmest fills.'),
        ('Do cooling pillows actually stay cool all night?', 'Phase-change material (PCM) pillows and covers absorb heat for the first 2-3 hours then release it. They cool the pillow during the warmest part of sleep onset but warm to body temperature by midnight. Water-filled pillows maintain cooler temperatures longer. Actively ventilated pillows (copper-infused, latex, buckwheat) stay consistently closer to room temperature.'),
        ('How long does a cooling pillow last?', 'Shredded memory foam pillows typically last 3-5 years before losing loft and support. Latex pillows last 5-8 years. Buckwheat hull pillows last 10+ years (hulls can be replaced). PCM covers lose cooling effectiveness over 3-4 years as the phase-change material degrades. The cooling mechanism degrades faster than the structural integrity in most pillows.'),
    ],
    'best-cpap-alternatives': [
        ('What are the alternatives to CPAP for sleep apnea?', 'The main CPAP alternatives are: (1) Mandibular Advancement Devices (MAD) -- custom or OTC mouthguards that reposition the jaw to open the airway, effective for mild to moderate OSA; (2) Positional therapy -- devices that prevent back sleeping for those with positional sleep apnea; (3) EPAP (Expiratory Positive Airway Pressure) -- nasal valves that create backpressure on exhalation; (4) Surgery -- uvulopalatopharyngoplasty (UPPP) or tongue base procedures; (5) Weight loss -- particularly effective for obesity-related OSA.'),
        ('Can I treat sleep apnea without CPAP?', 'Mild to moderate sleep apnea (AHI 5-30) may be managed without CPAP using a well-fitted MAD, positional therapy, or significant weight loss. Severe sleep apnea (AHI >30) typically requires CPAP or surgical intervention for adequate treatment. Always consult a sleep medicine specialist before stopping CPAP therapy -- undertreated sleep apnea significantly increases cardiovascular and metabolic disease risk.'),
        ('Are MADs as effective as CPAP?', 'For mild to moderate sleep apnea, custom-fitted MADs achieve similar quality-of-life outcomes to CPAP despite technically lower AHI reduction. Compliance is the key factor: CPAP works better when worn consistently, but patients use MADs more consistently (average 6-7 hours vs. 4-5 hours for CPAP). In real-world use, patient compliance often makes MADs comparably effective.'),
    ],
    'best-grounding-sheets': [
        ('Is there scientific evidence for grounding sheets?', 'The science on grounding (earthing) is mixed. Some small studies (many conducted by proponents of grounding products) report benefits: reduced inflammation markers, improved sleep quality, and reduced cortisol variability. However, these studies are small, often not double-blind, and not yet replicated in large independent trials. The physiological mechanism -- electrons from the earth neutralizing free radicals -- is plausible but not well-established. Grounding sheets may help some people, but the evidence is not strong enough for mainstream medical endorsement.'),
        ('How do grounding sheets work?', 'Grounding sheets contain conductive fibers (silver or carbon) woven into the fabric. These connect via a grounding cord to the ground port of a standard electrical outlet (or a ground stake outdoors). The connection supposedly equalizes the body with the earth\'s electrical potential, reducing electrostatic charge. The sheets must maintain skin contact and the ground connection must be secure to function as intended.'),
        ('Are grounding sheets safe to use?', 'Yes, grounding sheets are electrically safe when used as directed. The grounding port of an outlet carries no voltage -- it is only connected to the earth. There is no current flow through the user. The risk is using a cord with a damaged ground port or connecting to something other than the ground port. Use a continuity tester to verify your ground connection before regular use.'),
    ],
    'best-humidifiers-sleep': [
        ('What humidity level is best for sleep?', 'The optimal bedroom humidity for sleep is 40-60% relative humidity. Below 30%, the air causes dry nasal passages, throat irritation, and snoring. Above 60%, mold and dust mites thrive, and high humidity can worsen allergies and asthma. A hygrometer (humidity meter) lets you monitor your bedroom level precisely -- many smart humidifiers include one.'),
        ('Should I run a humidifier all night?', 'Yes, for consistent humidity benefits. Set your humidifier to a target humidity (40-50% RH) and let it run automatically. Most modern humidifiers have auto-shutoff when the target humidity is reached. Running a humidifier continuously without a humidity sensor can over-humidify, which promotes mold growth. Clean the water tank every 2-3 days to prevent bacterial growth.'),
        ('What type of humidifier is best for a bedroom?', 'Ultrasonic cool-mist humidifiers are the most popular for bedrooms -- they are quiet, energy-efficient, and do not produce heat. Evaporative humidifiers naturally self-regulate and cannot over-humidify but use more energy. Warm-mist humidifiers kill bacteria with heat but are a burn risk and not recommended near children. For a bedroom, ultrasonic with a built-in hygrometer and auto-shutoff is the best choice.'),
    ],
    'best-light-therapy-lamps': [
        ('How does light therapy improve sleep?', 'Light therapy (10,000 lux for 20-30 minutes each morning) resets the circadian clock by suppressing residual melatonin production and signaling the brain that morning has arrived. This advances the sleep-wake cycle, making it easier to wake early and fall asleep at night. It is most effective for Seasonal Affective Disorder (SAD), delayed sleep phase syndrome, and jet lag adjustment.'),
        ('When should I use a light therapy lamp?', 'Use your light therapy lamp within 30 minutes of waking, for 20-30 minutes, while eating breakfast or working. Consistency matters more than duration. Do not use it in the evening -- light exposure after 6pm delays melatonin onset and can worsen insomnia. The morning timing is what shifts the circadian clock forward.'),
        ('Are light therapy lamps safe for everyone?', 'Light therapy is generally safe, but with caveats. People with bipolar disorder should use it only under medical supervision -- bright light can trigger manic episodes. Those with photosensitive skin conditions or taking photosensitizing medications (some antibiotics, lithium, St. John\'s Wort) should consult a doctor first. Mild side effects (headache, eye strain) are common and usually resolve by adjusting distance or session length.'),
    ],
    'best-mattress-toppers': [
        ('Will a mattress topper fix a sagging mattress?', 'A mattress topper masks sagging but does not fix it. Toppers work by adding a new comfort layer on top, temporarily obscuring the uneven surface below. However, a deeply sagging mattress (2+ inch impression) will eventually show through the topper as it compresses. A topper extends the life of a marginally worn mattress, but a severely sagging mattress needs replacement.'),
        ('What thickness mattress topper should I get?', '2-inch toppers change the feel slightly while maintaining the mattress\'s original support structure. 3-inch toppers significantly alter pressure relief and are the standard recommendation for changing firmness. 4-inch toppers essentially replace the top half of your mattress comfort system and are best for severe firmness correction. If your mattress is in good structural shape, 2-3 inches is usually sufficient.'),
        ('Can a mattress topper make a firm mattress softer for side sleeping?', 'Yes -- a 2-3 inch soft latex or memory foam topper is the most cost-effective way to add pressure relief to a too-firm mattress for side sleepers. A medium-soft memory foam or soft Talalay latex topper (ILD 15-20) creates meaningful shoulder and hip relief. This is significantly cheaper than replacing a mattress that is otherwise structurally sound.'),
    ],
    'best-mattresses-back-pain': [
        ('What mattress firmness is best for lower back pain?', 'Medium-firm mattresses (5.5-7 on a 10-point scale) are the clinical consensus best choice for lower back pain. A 2015 Lancet study found medium-firm mattresses significantly improved pain and disability compared to firm mattresses. The goal is a mattress that supports the natural lumbar curve without allowing the hips to sink. The optimal firmness depends on body weight and sleep position.'),
        ('Does a firm mattress help back pain?', 'The "firm is best for back pain" belief is outdated. Research from the last 20 years consistently shows medium-firm outperforms firm for most back pain sufferers. A too-firm mattress creates pressure at the tailbone and upper back while leaving the lumbar unsupported. The exception is stomach sleepers with back pain, who genuinely benefit from firmer support.'),
        ('How often should I replace my mattress if I have back pain?', 'Replace your mattress when it shows visible sagging (1+ inch impression) or when morning back pain noticeably worsens compared to when the mattress was new. Most quality mattresses last 7-10 years. If your back pain is new and your mattress is older than 8 years, the mattress may be a contributing factor.'),
    ],
    'best-mattresses-couples-2026': [
        ('What is the most important mattress feature for couples?', 'Motion isolation is the top priority for most couples, followed by edge support. Motion isolation prevents one partner\'s movements from waking the other. Memory foam and pocket coil hybrids excel at motion isolation; traditional innerspring mattresses perform poorly. Edge support determines how much usable sleeping area you have -- strong edges let both partners sleep near the edge without rolling off.'),
        ('What firmness works for couples with different preferences?', 'Split firmness (different firmness on each side) is available from Saatva, Helix, Sleep Number, and other brands. For couples without access to a split option, medium (5-6/10) is the best compromise for side sleepers, combination sleepers, and back sleepers -- it is the firmness that works reasonably well for the widest range of body types and positions.'),
        ('What size mattress is best for couples?', 'A Queen is the minimum comfortable size for most couples (60x80 inches). A King gives each partner the equivalent of a Twin XL to themselves (76x80 inches). A California King is longer (72x84) but slightly narrower than King -- better for very tall couples. For couples with children or pets who share the bed, a King is strongly recommended.'),
    ],
    'best-melatonin-supplements': [
        ('What is the correct melatonin dose for sleep?', 'Most adults need only 0.5-1mg of melatonin, not the 5-10mg doses commonly sold. A landmark study by the MIT scientist who discovered melatonin\'s sleep role found 0.3-1mg as effective as higher doses for shifting circadian timing, with fewer next-day side effects. Start at 0.5mg and increase only if needed. Higher doses saturate melatonin receptors without additional benefit.'),
        ('Can you take melatonin every night?', 'Short-term nightly use (1-4 weeks) is safe and often appropriate for jet lag, shift work adjustment, and sleep schedule correction. Long-term nightly use is less studied. The primary concern is not melatonin dependency but rather masking an underlying sleep disorder that should be addressed. If you need melatonin to fall asleep every night, consult a sleep specialist about CBT-I and other behavioral approaches.'),
        ('What form of melatonin works fastest?', 'Sublingual (under-the-tongue) liquid or tablet melatonin absorbs fastest -- typically within 15-20 minutes. Gummies and standard tablets dissolve in 20-40 minutes. Extended-release tablets work for sleep maintenance (staying asleep) but not sleep onset. Take immediate-release melatonin 30-60 minutes before your intended sleep time.'),
    ],
    'best-pillow-sleep-position': [
        ('How do I know what type of pillow I need?', 'Your sleep position determines pillow loft (height) and firmness. Side sleepers need high-loft (4-6 inch) firm pillows to fill the gap between shoulder and head. Back sleepers need medium-loft (3-4 inch) medium-firm pillows to maintain cervical curve. Stomach sleepers need very flat (1-2 inch) soft pillows to prevent neck extension. Combination sleepers do best with adjustable fill.'),
        ('How often should pillows be replaced?', 'Polyester fill pillows: every 1-2 years. Memory foam and latex pillows: every 3-5 years. Down pillows: every 5-7 years with proper care. A simple fold test: fold your pillow in half -- if it does not spring back, it has lost its support and should be replaced. Pillows also accumulate 2-3 years of skin cells, dust mites, and oils regardless of appearance.'),
        ('Does pillow height affect neck pain?', 'Yes -- pillow height is one of the most direct causes of cervical spine misalignment. A too-tall pillow flexes the neck forward for hours; a too-flat pillow extends it backward. The ideal pillow keeps the head in line with the spine. Side sleepers tend to need taller pillows (shoulder-width dependent); back sleepers need medium height; stomach sleepers need very flat or no pillow.'),
    ],
    'best-sleep-apps': [
        ('Do sleep tracking apps actually work?', 'Sleep apps that use the phone microphone or accelerometer to track sleep stages are less accurate than wearable devices. Consumer-grade sleep stage tracking (light/deep/REM) is typically 70-80% accurate compared to polysomnography. Sound-based snore detection and sleep timing tracking are more reliable. Apps are useful for identifying patterns and trends over weeks, but individual night readings should be interpreted with skepticism.'),
        ('What is the best free sleep app?', 'Sleep Cycle (iOS/Android) offers sound-based sleep tracking with a smart alarm that wakes you in light sleep -- free tier is useful. Insight Timer is excellent for guided sleep meditations (free). Calm and Headspace have strong sleep content but are subscription-based. For CBT-I (cognitive behavioral therapy for insomnia), Sleepio and Somryst are FDA-cleared but typically require prescription or insurance.'),
        ('Can a sleep app help with insomnia?', 'Sleep apps with evidence-based CBT-I content can help with chronic insomnia. The American College of Physicians recommends CBT-I as the first-line treatment for chronic insomnia over sleep medications. Apps like Sleepio have clinical data showing efficacy comparable to in-person CBT-I. Simple sleep tracking apps alone do not treat insomnia -- the intervention content matters.'),
    ],
    'best-sleep-headphones': [
        ('Are sleep headphones safe to wear all night?', 'Yes, when used properly. The main risks are: ear canal damage from in-ear headphones at high volume for long periods (keep volume below 60dB); physical discomfort from pressure of over-ear headphones if you are a side sleeper; and tangling hazards with wired headphones. Flat sleep headphone headbands (like Musicozy or Perytong) are designed for side sleeping and minimize pressure risks.'),
        ('What is the best noise-canceling option for sleeping?', 'For sleeping, passive noise isolation (good seal, soft foam tips) often outperforms active noise canceling (ANC) because ANC generates a low-frequency hiss that can be audible in quiet rooms. For loud environments (snoring partner, street noise), a combination of ANC and pink/white noise masking is more effective than ANC alone. Bose QuietComfort and Sony WH-1000XM5 are the benchmark ANC headphones, but their size makes side sleeping difficult.'),
        ('Do bone conduction headphones work for sleeping?', 'Bone conduction headphones (Shokz, Vidonn) sit against the cheekbones rather than in or over the ears, leaving ears open. They work well for sleeping because they reduce ear pressure and allow ambient sound (important for safety). Sound quality is lower than in-ear options, but for white noise, podcasts, or audiobooks during sleep, bone conduction is comfortable and practical.'),
    ],
    'best-sleep-masks': [
        ('Do sleep masks actually improve sleep quality?', 'Yes -- multiple studies confirm sleep masks improve sleep quality. A 2010 study found sleep masks and earplugs significantly increased REM sleep and melatonin levels in ICU patients. Complete darkness is one of the strongest signals for melatonin production -- even light through closed eyelids can suppress melatonin. For light sleepers, travelers, and shift workers, a well-fitted sleep mask is one of the highest-impact low-cost sleep improvements.'),
        ('What makes a good sleep mask?', 'Total light blockage is the primary function -- look for masks with nose bridges or contoured cups that prevent light from entering at the sides. Contoured masks with eye cups (like the Alaska Bear or Manta) prevent pressure on eyelids and allow REM eye movement. For fabric, silk is cool and gentle on skin; memory foam contoured masks are most light-blocking. Weight: under 1 oz is ideal to avoid pressure headaches.'),
        ('Can sleep masks cause eye problems?', 'Standard sleep masks do not damage eyes when worn correctly. The concern is eye pressure -- masks that press directly on the eyelids can temporarily increase intraocular pressure. Contoured or cupped masks that create space around the eyes prevent this entirely. If you have glaucoma or high intraocular pressure, use a cupped/contoured design that maintains a pressure-free eye cavity.'),
    ],
    'best-sleep-monitors': [
        ('How accurate are consumer sleep monitors?', 'Consumer sleep monitors (wearables, bedside devices) track sleep stages with 70-80% accuracy compared to clinical polysomnography (the gold standard). They are reliable for tracking sleep timing and duration, and reasonably reliable for identifying sleep stage patterns over time. Single-night sleep stage data from a consumer device should not be used for clinical decisions. Trends over 2-4 weeks are more meaningful than individual nights.'),
        ('What is the best sleep monitor without a wearable?', 'Bedside non-contact monitors like the Withings Sleep Analyzer use ballistocardiography (body movement and heart rate detected through the mattress surface) to track sleep without wearing anything. Accuracy is similar to wrist-based wearables. The radar-based Google Nest Hub (2nd gen) and the Emfit QS are other solid non-wearable options. For contact-free tracking, mattress sensor pads outperform phone-based tracking.'),
        ('Should I sleep with my phone next to my bed for sleep tracking?', 'Not ideal. Phone-based sleep tracking is less accurate than dedicated wearables and requires keeping your phone near the bed (with potential blue light and notification exposure). If you use a phone for sleep tracking, put it face-down on airplane mode with only the alarm active. A dedicated wearable or bedside sensor is preferable.'),
    ],
    'best-sleep-position': [
        ('What is the healthiest sleep position?', 'Back sleeping on a medium-firm mattress is generally considered optimal for spinal alignment -- it keeps the spine in its natural curves without lateral bending or rotation. However, back sleeping is the worst position for snoring and sleep apnea. Side sleeping (left side preferred for acid reflux and pregnancy) is an excellent second choice with proper pillow support. Stomach sleeping is the least spinal-friendly position.'),
        ('Can changing sleep positions improve back pain?', 'Yes. Many back pain cases are position-related. Common fixes: side sleepers should place a pillow between the knees to prevent hip rotation. Back sleepers should place a pillow under the knees to reduce lumbar pressure. Stomach sleepers should transition to side sleeping to eliminate the neck rotation and lumbar extension of prone sleeping. Position changes often produce noticeable improvement within 1-2 weeks.'),
        ('How do I train myself to sleep on my back?', 'Place pillows on both sides of your body to create a "channel" that prevents rolling to your side. A body pillow on your favored side creates resistance. Elevating the head of the bed 10-15 degrees with adjustable base reduces the discomfort many people feel lying flat on their backs. Expect 2-4 weeks to adapt to a new sleep position.'),
    ],
    'best-sleep-supplements-guide': [
        ('Which sleep supplement is most effective?', 'For evidence and safety, magnesium glycinate and melatonin (at low doses, 0.5-1mg) have the strongest clinical support. CBT-I (cognitive behavioral therapy for insomnia) outperforms all supplements for chronic insomnia but is not a supplement. Ashwagandha (KSM-66) has good evidence for stress-related sleep disruption. L-theanine has mild supporting evidence for sleep quality. Avoid over-the-counter diphenhydramine (Benadryl/ZzzQuil) for regular use -- tolerance develops within days.'),
        ('Are sleep supplements safe long-term?', 'Magnesium glycinate is safe for long-term use -- it addresses a common deficiency without dependency. Melatonin is safe for short-term and situational use; long-term nightly use is less studied. Ashwagandha is safe for 3-6 month continuous use with some evidence of sustained benefit. Valerian root has a mixed safety profile long-term. Pharmaceutical sleep aids (benzodiazepines, Z-drugs) cause dependency and should not be used long-term.'),
        ('Should I take sleep supplements before or after a meal?', 'Most sleep supplements are better absorbed with a small snack: magnesium glycinate with a light meal 30-60 minutes before bed. Melatonin on an empty stomach is fine and may absorb faster. Ashwagandha with food reduces potential gastric discomfort. L-theanine can be taken anytime. Valerian root: 30-60 minutes before bed, with or without food.'),
    ],
    'best-sleep-tracking-rings': [
        ('Are sleep tracking rings more accurate than smartwatches?', 'Rings are generally considered slightly more accurate than wrist-based smartwatches for sleep tracking because finger capillaries provide cleaner photoplethysmography (PPG) heart rate readings than the wrist, which is affected by wrist movement and pressure variations. The Oura Ring is the most validated consumer sleep tracker against polysomnography. However, differences between top-tier rings and watches (Apple Watch, Garmin) are modest in practice.'),
        ('How long does the Oura Ring battery last?', 'The Oura Ring Gen 3 lasts 4-7 days per charge, depending on use. This is longer than most smartwatches (1-3 days), making it more practical for continuous sleep tracking. Charging takes about 1 hour. The Ultrahuman Ring Air and Samsung Galaxy Ring have similar battery life in the 4-7 day range.'),
        ('Do sleep tracking rings require a subscription?', 'The Oura Ring requires a $5.99/month subscription for full access to sleep scores and health insights. Basic data is accessible without subscription. Ultrahuman Ring Air has no subscription. Samsung Galaxy Ring integrates with Samsung Health which is free. RingConn has no subscription. If avoiding subscriptions, Ultrahuman and RingConn are the best alternatives to Oura.'),
    ],
    'best-smart-mattresses': [
        ('What can a smart mattress actually do?', 'Smart mattresses range from basic (sleep tracking, temperature logging) to advanced (active temperature control, firmness adjustment, snoring detection, partner separation). Eight Sleep Pod tracks sleep stages, heart rate, and breathing rate while actively heating/cooling each side independently. Sleep Number 360 offers firmness adjustment mid-sleep via air chambers. FlipSide and other platforms integrate with smart home systems.'),
        ('Are smart mattresses worth the premium price?', 'For hot sleepers, the Eight Sleep Pod\'s active cooling delivers measurable sleep improvement and may justify the $2,000+ price for those who consistently sleep hot. For couples with different firmness preferences, Sleep Number eliminates mattress compromise. For most people, a quality traditional mattress at $1,000-1,500 plus a separate cooling pad at $200-500 achieves similar outcomes at lower cost.'),
        ('Do smart mattresses require internet connection?', 'Most smart mattress features require WiFi for app connectivity, firmware updates, and cloud-based sleep analytics. Local features (firmness adjustment, basic temperature) often work offline. The Eight Sleep requires internet for AI coaching and temperature scheduling. Sleep Number can adjust firmness locally via the remote without internet. Check connectivity requirements before purchase if internet reliability is a concern.'),
    ],
    'best-valerian-root-supplements': [
        ('Does valerian root actually work for sleep?', 'The evidence is mixed. Some meta-analyses show valerian improves sleep quality and reduces sleep latency; others find no significant benefit over placebo. The inconsistency may be due to variation in root preparation quality -- valerian\'s active compounds (valerenic acid, isovaleric acid) are unstable and degrade quickly if improperly stored or processed. Standardized extracts with guaranteed valerenic acid content perform more consistently than whole-root powder.'),
        ('How long does it take for valerian to work for sleep?', 'Unlike melatonin (which works within 30-60 minutes), valerian typically requires 2-4 weeks of nightly use to show cumulative benefit. Do not evaluate valerian based on one or two nights. Take it nightly for 30 days and assess overall sleep quality trends. Some people notice immediate mild sedation; others require consistent use to see benefit.'),
        ('Can I take valerian root with melatonin?', 'Yes, valerian and melatonin are commonly combined. They work through different mechanisms: valerian is thought to act on GABA receptors (similar to benzodiazepines but much milder); melatonin signals sleep timing through the circadian system. Combined use at standard doses is generally considered safe. Avoid combining with alcohol, sedating medications, or other herbal sedatives without medical guidance.'),
    ],
}

updated = 0
for slug, faqs in FAQ_DATA.items():
    path = os.path.join(POSTS_DIR, f'{slug}.html')
    if not os.path.exists(path):
        print(f'NOT FOUND: {slug}')
        continue

    with open(path, encoding='utf-8') as f:
        html = f.read()

    if 'FAQPage' in html:
        print(f'SKIP (has FAQPage): {slug}')
        continue

    schema = {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
            {'@type': 'Question', 'name': q, 'acceptedAnswer': {'@type': 'Answer', 'text': a}}
            for q, a in faqs
        ]
    }
    block = '<script type="application/ld+json">\n' + json.dumps(schema, indent=2) + '\n</script>'

    if '</head>' not in html:
        print(f'NO HEAD: {slug}')
        continue

    html2 = html.replace('</head>', block + '\n</head>', 1)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html2)
    print(f'OK: {slug}')
    updated += 1

print(f'\nTotal updated: {updated}')
